name: PagerDuty Maintenance Window

on:
  workflow_dispatch:
    inputs:
      duration_minutes:
        description: 'Duration in minutes'
        required: true
        type: number
        default: 15
      select_all:
        description: 'Select all services'
        type: boolean
        required: false
        default: true
      service_P1DF299:
        description: 'P1DF299'
        type: boolean
        required: false
      service_PJ5CTRB:
        description: 'PJ5CTRB'
        type: boolean
        required: false
      service_P86XAY9:
        description: 'P86XAY9'
        type: boolean
        required: false
      service_PUTC765:
        description: 'PUTC765'
        type: boolean
        required: false
      service_PYNFRNY:
        description: 'PYNFRNY'
        type: boolean
        required: false
      service_PEA4386:
        description: 'PEA4386'
        type: boolean
        required: false
      maintenance_description:
        description: 'Description of maintenance work'
        required: true
        type: string
        default: 'Maintenance window'

jobs:
  create-maintenance-window:
    runs-on: ubuntu-latest
    steps:
      - name: Process Selected Services
        id: services
        run: |
          selected_ids=()
          
          if [[ "${{ inputs.select_all }}" == "true" ]]; then
            selected_ids=("P1DF299" "PJ5CTRB" "P86XAY9" "PUTC765" "PYNFRNY" "PEA4386")
          else
            if [[ "${{ inputs.service_P1DF299 }}" == "true" ]]; then
              selected_ids+=("P1DF299")
            fi
            if [[ "${{ inputs.service_PJ5CTRB }}" == "true" ]]; then
              selected_ids+=("PJ5CTRB")
            fi
            if [[ "${{ inputs.service_P86XAY9 }}" == "true" ]]; then
              selected_ids+=("P86XAY9")
            fi
            if [[ "${{ inputs.service_PUTC765 }}" == "true" ]]; then
              selected_ids+=("PUTC765")
            fi
            if [[ "${{ inputs.service_PYNFRNY }}" == "true" ]]; then
              selected_ids+=("PYNFRNY")
            fi
            if [[ "${{ inputs.service_PEA4386 }}" == "true" ]]; then
              selected_ids+=("PEA4386")
            fi
          fi
          
          service_ids=$(IFS=,; echo "${selected_ids[*]}")
          echo "service_ids=$service_ids" >> $GITHUB_OUTPUT
          echo "Selected services: $service_ids"

      - name: Validate Selection
        run: |
          if [[ -z "${{ steps.services.outputs.service_ids }}" ]]; then
            echo "Error: Please select at least one service or choose 'Select all services'"
            exit 1
          fi

      - name: Create PagerDuty Maintenance Window
        id: maintenance-window
        uses: im-open/open-pagerduty-maintenance-window@v1.3.1
        with:
          pagerduty-api-key: ${{ secrets.PAGERDUTY_API_KEY }}
          service-ids: ${{ steps.services.outputs.service_ids }}
          description: ${{ inputs.maintenance_description }}
          minutes: ${{ inputs.duration_minutes }}

      - name: Output Window Details
        run: |
          echo "Maintenance Window ID: ${{ steps.maintenance-window.outputs.maintenance-window-id }}"
          echo "Selected Services: ${{ steps.services.outputs.service_ids }}"
          echo "Duration: ${{ inputs.duration_minutes }} minutes"
